Implement threshold decision policy
regen-network/cosmos-modules pull request #55
Opened 2020-03-17 13:49 UTC by alpe

Resolves #45

After #54

2020-03-31 16:53 UTC, aaronc requested changes
The tests look good but I realize that the threshold policy is actually incorrectly specified. The threshold must be _met or_ exceeded. Just exceeding it is counter intuitive because in order to have a 1 out of 3 policy, you would need to set the threshold to 0. Looks like I messed up with my initial specification. My apologies!

2020-03-31 16:53 UTC, aaronc commented on incubator/group/types.go
> +// DecisionPolicy persistent ruleset to determine the result of election on a proposal.
```suggestion
// DecisionPolicy is persistent set of rules to determine the result of election on a proposal.
```

2020-03-31 16:53 UTC, aaronc commented on incubator/group/types.go
> +// Allow allow a proposal to pass when the threshold is exceeded by yes votes before the timeout.
```suggestion
// Allow allows a proposal to pass when the tally of yes votes equals or exceeds the threshold before the timeout.
```

2020-03-31 16:53 UTC, aaronc commented on incubator/group/types.proto
>      // threshold is a fix weight value that must be exceeded for a proposal to succeed.
```suggestion
    // threshold is a fix weight value that must be met or exceeded for a proposal to succeed.
```

2020-03-31 16:53 UTC, aaronc commented on incubator/group/types_test.go
> +		"reject when yes count equal to threshold": {
```suggestion
		"accept when yes count equal to threshold": {
```

2020-03-31 16:53 UTC, aaronc commented on incubator/group/types_test.go
> +			expResult:         DecisionPolicyResult{Allow: false, Final: false},
```suggestion
			expResult:         DecisionPolicyResult{Allow: true, Final: true},
```

2020-03-31 16:53 UTC, aaronc commented on incubator/group/types_test.go
> +		"reject as final when remaining votes can't cross threshold": {
Update according to new definition of threshold

2020-03-31 16:53 UTC, aaronc commented on incubator/group/types_test.go
> +		"abstain has not impact": {
```suggestion
		"abstain has no impact": {
```

2020-04-01 12:42 UTC, alpe commented
I have modified the policy. With equal numbers we need to prohibit threshold==0, now so that we have a least 1 yes vote.

2020-04-01 17:06 UTC, aaronc requested changes
Just found another minor doc type. Otherwise LGTM and ready to merge.

2020-04-01 17:06 UTC, aaronc commented on incubator/group/types.go
> +// DecisionPolicy is persistent set of rules to determine the result of election on a proposal.
```suggestion
// DecisionPolicy is the persistent set of rules to determine the result of election on a proposal.
```

2020-04-02 07:13 UTC, alpe commented
I had applied the change. Waiting for your approval (on github)

2020-04-02 13:11 UTC, aaronc approved these changes

2020-04-02 15:50 UTC, merged